# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-02 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_auto_20180502_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(auto_now=True),
        ),
    ]
