# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-02 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_perfil_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
