# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-02 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0008_auto_20180502_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
