# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-03 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0009_auto_20180502_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='agenda_cita',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='identificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seguridad.Municipio'),
        ),
    ]
