# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-16 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineatiempo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='num_img',
            field=models.IntegerField(default=0),
        ),
    ]
