# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-02 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineatiempo', '0002_publicacion_num_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariop',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/images/publicaciones'),
        ),
    ]
