# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-16 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineatiempo', '0003_comentariop_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariop',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='static/images/publicaciones'),
        ),
    ]
