# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='entrevista1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='entrevista2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='entrevista3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='entrevista4',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='entrevista5',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='video',
            field=models.CharField(max_length=500),
        ),
    ]
