# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-19 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0004_auto_20180906_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subTitulo', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('video', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Videos Con-Ciencia Familiar',
            },
        ),
    ]
