# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-18 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0002_auto_20180618_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(default=None, null=True, upload_to='static/images/mesa')),
                ('acciones', models.TextField()),
                ('actores', models.TextField()),
                ('requerimientos', models.TextField()),
                ('compromisos', models.TextField()),
                ('plazo', models.DateField(default=None, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Municipio')),
            ],
            options={
                'verbose_name_plural': 'planes',
            },
        ),
    ]
