# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-18 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='estado',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
