# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-18 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0002_auto_20180618_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='plazo',
        ),
    ]
