# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-18 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0005_remove_plan_plazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plazo',
            field=models.DateField(default=None, null=True),
        ),
    ]
