# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100)),
                ('respuesta', models.TextField()),
                ('link1', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('link2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('video', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'preguntas frecuentes',
            },
        ),
    ]
