# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='descripcion_link1',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='descripcion_link2',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
