kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redsentir-pvc
  namespace: redsentir
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
