# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='static/images/avatar/')),
                ('descripcion', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
