# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-10 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_auto_20170912_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subTitulo', models.CharField(max_length=50, null=True)),
                ('imagen', models.ImageField(upload_to='static/images/pagina/noticia')),
                ('descripcion', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
