# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-10 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
