# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-27 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_auto_20171009_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrusel',
            options={'verbose_name_plural': 'carruseles'},
        ),
    ]
