# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-02 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
