# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-27 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0006_auto_20171027_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foro',
            options={'permissions': (('recibe_notificaciones', 'responder_comentario'),)},
        ),
    ]
