# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0008_comentario_me_gusta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foro',
            options={'permissions': (('recibe_notificaciones', 'recibe_notificaciones'),)},
        ),
        migrations.AddField(
            model_name='comentario',
            name='respuestas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='me_gusta',
            field=models.IntegerField(default=0),
        ),
    ]
