# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-13 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0009_auto_20171031_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foro',
            old_name='introduccion',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='foro',
            name='tema',
            field=models.TextField(),
        ),
    ]
