# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-13 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0010_auto_20171213_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='introduccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foro',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
