# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0009_auto_20180502_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primera_vez', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('fecha_revision', models.DateTimeField(auto_now=True)),
                ('fecha_cita', models.DateTimeField(auto_now=True)),
                ('observaciones', models.CharField(max_length=200)),
                ('estado', models.CharField(default='activa', max_length=20)),
                ('calificacion', models.IntegerField(default=0)),
                ('observaciones_joven', models.CharField(max_length=200)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Perfil')),
            ],
        ),
    ]
