# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-18 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('introduccion', models.CharField(max_length=200)),
                ('tema', models.TextField()),
                ('imagen', models.ImageField(default='static/images/foros/defaultUser.png', upload_to='static/images/foros/')),
            ],
        ),
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Municipio')),
                ('responsables', models.ManyToManyField(to='seguridad.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primera_vez', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('fecha_revision', models.DateTimeField(auto_now=True)),
                ('fecha_cita', models.DateTimeField(blank=True, default=None, null=True)),
                ('observaciones', models.CharField(max_length=200)),
                ('profesional', models.CharField(max_length=200)),
                ('estado', models.CharField(default='activa', max_length=20)),
                ('calificacion', models.IntegerField(default=0)),
                ('observaciones_joven', models.CharField(max_length=200)),
                ('ips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Ips')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Perfil')),
            ],
        ),
    ]
