# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-03 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('introduccion', models.CharField(max_length=200)),
                ('tema', models.TextField()),
                ('imagen', models.ImageField(default='static/images/foros/defaultUser.png', upload_to='static/images/foros/')),
            ],
        ),
    ]
