# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-12 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0010_auto_20180503_1321'),
        ('servicios', '0002_informacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Municipio')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='identificacion',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='telefono',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='primera_vez',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicio',
            name='ips',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicios.Ips'),
            preserve_default=False,
        ),
    ]
