# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-12 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0010_auto_20180503_1321'),
        ('servicios', '0003_auto_20180512_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='ips',
            name='responsables',
            field=models.ManyToManyField(to='seguridad.Perfil'),
        ),
    ]
