# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_ips_responsables'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='profesional',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
