# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-15 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_servicio_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_cita',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
