# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-15 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20180515_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='ips',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
